name: Run tests and deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install dependencies
        run: | 
          npm install 
          npm install -g allure-commandline
          npm install -g playwright
          
      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run tests
        run: npm run test

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: allure-report
